package org.neteinstein.couples.data.analytics

import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.json.Json
import org.neteinstein.couples.domain.analytics.AnalyticsEvent
import org.neteinstein.couples.domain.analytics.AnalyticsScreen
import org.neteinstein.couples.domain.analytics.AnalyticsTracker
import org.neteinstein.couples.domain.analytics.AnalyticsUserProperty

/**
 * Web [AnalyticsTracker], talking to the Firebase JS SDK through the small `globalThis`-scoped
 * bridge that `firebase-init.js` installs (generated by `:webApp:generateFirebaseWebInit` - see
 * `webApp/build.gradle.kts`).
 *
 * It goes through a JS bridge rather than a Kotlin/Wasm binding to the `firebase` npm package
 * because the modular Firebase Web SDK is ESM-only and tree-shaken at bundle time; pulling it into
 * the Kotlin/Wasm webpack build would mean npm dependency management in the Gradle build for what
 * is ultimately four function calls. The bridge loads the SDK straight from `gstatic.com` as an ES
 * module instead, which also keeps the whole Firebase config out of the compiled wasm binary.
 *
 * Every call is null-safe on the JS side: if `firebase-init.js` found no configuration (a local
 * build with no Firebase secrets set) or the user has opted out, `globalThis.__coupleMomentsAnalytics`
 * is simply never defined and each bridge function below does nothing. That is the Web equivalent
 * of Android falling back to [NoOpAnalyticsTracker].
 */
class FirebaseWebAnalyticsTracker : AnalyticsTracker {
    override val platform: String = PLATFORM_WEB

    override fun setCollectionEnabled(enabled: Boolean) {
        webSetCollectionEnabled(enabled)
    }

    override fun setUserId(userId: String?) {
        // The bridge maps "" back to null - Kotlin nullability doesn't survive the wasm/JS
        // boundary for a plain String parameter.
        webSetUserId(userId ?: "")
    }

    override fun setUserProperty(
        property: AnalyticsUserProperty,
        value: String?,
    ) {
        webSetUserProperty(property.key, value ?: "")
    }

    override fun logScreenView(screen: AnalyticsScreen) {
        webLogEvent(
            EVENT_SCREEN_VIEW,
            encodeParams(
                mapOf(
                    PARAM_SCREEN_NAME to screen.screenName,
                    PARAM_SCREEN_CLASS to screen.screenName,
                ),
            ),
        )
    }

    override fun logEvent(event: AnalyticsEvent) {
        webLogEvent(event.name, encodeParams(event.params))
    }

    /**
     * Parameters cross into JS as a JSON string the bridge `JSON.parse`s. Building a `JsAny`
     * object graph field by field from Kotlin/Wasm would need one `js()` helper per arity; one
     * serialized string handles any shape and gets the escaping right for free.
     */
    private fun encodeParams(params: Map<String, String>): String = Json.encodeToString(paramsSerializer, params)

    private companion object {
        const val PLATFORM_WEB = "web"

        /** Firebase's own reserved screen-view event/parameter names, spelled out - the JS SDK
         * exposes no constants for them the way the Android SDK's `FirebaseAnalytics.Event` does. */
        const val EVENT_SCREEN_VIEW = "screen_view"
        const val PARAM_SCREEN_NAME = "screen_name"
        const val PARAM_SCREEN_CLASS = "screen_class"

        val paramsSerializer = MapSerializer(String.serializer(), String.serializer())
    }
}

// The four bridge calls. `js(...)` bodies are only allowed on top-level functions in Kotlin/Wasm,
// which is why these sit outside the class. Each one guards on the bridge existing, so an
// unconfigured or opted-out page is a no-op rather than a TypeError in the console.

private fun webLogEvent(
    name: String,
    paramsJson: String,
): Unit =
    js(
        """{
        if (globalThis.__coupleMomentsAnalytics) {
            globalThis.__coupleMomentsAnalytics.logEvent(name, paramsJson);
        }
    }""",
    )

private fun webSetUserId(userId: String): Unit =
    js(
        """{
        if (globalThis.__coupleMomentsAnalytics) {
            globalThis.__coupleMomentsAnalytics.setUserId(userId);
        }
    }""",
    )

private fun webSetUserProperty(
    name: String,
    value: String,
): Unit =
    js(
        """{
        if (globalThis.__coupleMomentsAnalytics) {
            globalThis.__coupleMomentsAnalytics.setUserProperty(name, value);
        }
    }""",
    )

private fun webSetCollectionEnabled(enabled: Boolean): Unit =
    js(
        """{
        if (globalThis.__coupleMomentsAnalytics) {
            globalThis.__coupleMomentsAnalytics.setCollectionEnabled(enabled);
        }
    }""",
    )
