plugins {
    id("kmp-web-application")
}

// ─── Firebase (Web) ─────────────────────────────────────────────────────────────────────────
//
// The Firebase JS SDK is loaded at runtime from gstatic.com as an ES module by the small
// firebase-init.js the task below writes; it is not a Gradle or npm dependency of this build.
// That keeps the Firebase config out of both the compiled wasm binary and this repository: the
// values come from the environment (CI secrets - see .github/workflows/deploy-pages.yml) or, for
// a local run, from Gradle properties.
//
// When no configuration is supplied the task still runs and still writes the file - it just
// writes the variant that installs no bridge at all. `FirebaseWebAnalyticsTracker` guards every
// call on that bridge existing, so an unconfigured build (any fork, any contributor, the PR "Web"
// CI job) behaves exactly like a configured one minus the reporting, with no 404 for a missing
// script and no console error.
//
// Note on "secrets": a Firebase *Web* config is not a credential the way a service-account key is
// - whatever ships to the browser is readable by anyone who opens devtools, and Firebase's access
// control is server-side (API key restrictions + security rules), not config secrecy. It is
// sourced from secrets here so it stays out of version control, not because that makes the
// deployed values private.
val firebaseWebConfigKeys =
    listOf(
        "apiKey" to "FIREBASE_WEB_API_KEY",
        "authDomain" to "FIREBASE_WEB_AUTH_DOMAIN",
        "projectId" to "FIREBASE_WEB_PROJECT_ID",
        "storageBucket" to "FIREBASE_WEB_STORAGE_BUCKET",
        "messagingSenderId" to "FIREBASE_WEB_MESSAGING_SENDER_ID",
        "appId" to "FIREBASE_WEB_APP_ID",
        "measurementId" to "FIREBASE_WEB_MEASUREMENT_ID",
    )

// Environment variable first (that is what CI sets), then the equivalent Gradle property
// (`-PfirebaseWeb.apiKey=...`, or a line in ~/.gradle/gradle.properties) for local runs. Both are
// read through `providers`, so the configuration cache invalidates correctly when either changes.
val firebaseWebConfig: Map<String, String> =
    firebaseWebConfigKeys
        .mapNotNull { (jsonKey, envName) ->
            providers
                .environmentVariable(envName)
                .orElse(providers.gradleProperty("firebaseWeb.$jsonKey"))
                .orNull
                ?.trim()
                ?.takeIf { it.isNotEmpty() }
                ?.let { jsonKey to it }
        }.toMap()

// Everything except measurementId is required for initializeApp/getAnalytics to work at all, so a
// half-filled config is treated as no config rather than shipped as a broken one - a mistyped
// secret name then shows up in the build log instead of silently collecting nothing.
val firebaseWebMissingKeys =
    (firebaseWebConfigKeys.map { it.first } - "measurementId")
        .filterNot { firebaseWebConfig.containsKey(it) }

/** JS string-literal escaping for the config values interpolated into the generated script. */
fun jsString(value: String): String = "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

/**
 * The real bridge: loads the modular Firebase Web SDK from gstatic and exposes the four calls
 * `FirebaseWebAnalyticsTracker` makes on `globalThis.__coupleMomentsAnalytics`.
 *
 * Analytics is not initialized at all when the user has opted out. The opt-out lives in
 * localStorage under `analytics_enabled` (multiplatform-settings' StorageSettings, written by
 * `AnalyticsConsentRepositoryImpl`), and it has to be read here rather than waited for: by the
 * time the wasm binary has loaded and could call setCollectionEnabled(false), `getAnalytics()`
 * would already have fired its own automatic page_view.
 */
fun firebaseInitScript(
    sdkVersion: String,
    config: Map<String, String>,
): String {
    val configLiteral = config.entries.joinToString(", ") { (key, value) -> "$key: ${jsString(value)}" }
    return """
        // GENERATED by :webApp:generateFirebaseWebInit - do not edit, do not commit.
        // Source: the FIREBASE_WEB_* environment variables / firebaseWeb.* Gradle properties.
        import { initializeApp } from "https://www.gstatic.com/firebasejs/$sdkVersion/firebase-app.js";
        import {
          getAnalytics,
          logEvent,
          setUserId,
          setUserProperties,
          setAnalyticsCollectionEnabled,
        } from "https://www.gstatic.com/firebasejs/$sdkVersion/firebase-analytics.js";

        // Written by AnalyticsConsentRepositoryImpl via multiplatform-settings' StorageSettings.
        // Absent means "not chosen yet", which defaults to opted in - as it does in Kotlin.
        const optedOut =
          !!globalThis.localStorage && globalThis.localStorage.getItem("analytics_enabled") === "false";

        // Whatever the queue stub in index.html buffered while this deferred module was waiting to
        // run. Read before the global is replaced below; dropped entirely when opted out.
        const pending = (globalThis.__coupleMomentsAnalytics || {}).pendingCalls || [];

        if (optedOut) {
          // Deleting the global is what makes every FirebaseWebAnalyticsTracker call a no-op - it
          // guards on this existing - so an opted-out page never loads or initializes Analytics.
          delete globalThis.__coupleMomentsAnalytics;
        } else {
          const app = initializeApp({ $configLiteral });
          const analytics = getAnalytics(app);

          // The surface FirebaseWebAnalyticsTracker calls. Every entry swallows its own errors: an
          // ad blocker or a tracking-protection setting makes these throw, and analytics must never
          // break the app.
          globalThis.__coupleMomentsAnalytics = {
            logEvent(name, paramsJson) {
              try {
                logEvent(analytics, name, paramsJson ? JSON.parse(paramsJson) : {});
              } catch (error) {
                console.debug("analytics logEvent failed", error);
              }
            },
            setUserId(id) {
              try {
                setUserId(analytics, id === "" ? null : id);
              } catch (error) {
                console.debug("analytics setUserId failed", error);
              }
            },
            setUserProperty(name, value) {
              try {
                setUserProperties(analytics, { [name]: value === "" ? null : value });
              } catch (error) {
                console.debug("analytics setUserProperty failed", error);
              }
            },
            setCollectionEnabled(enabled) {
              try {
                setAnalyticsCollectionEnabled(analytics, enabled);
              } catch (error) {
                console.debug("analytics setCollectionEnabled failed", error);
              }
            },
          };

          // Replay what was buffered, in order, now that the real bridge is in place.
          for (const [method, ...args] of pending) {
            globalThis.__coupleMomentsAnalytics[method](...args);
          }
        }
        """.trimIndent() + "\n"
}

/** The no-configuration variant: defines nothing, so every bridge call from Kotlin is a no-op. */
fun firebaseDisabledScript(missingKeys: List<String>): String =
    """
    // GENERATED by :webApp:generateFirebaseWebInit - do not edit, do not commit.
    // Firebase Web analytics is disabled in this build: no configuration was supplied
    // (missing: ${missingKeys.joinToString()}).
    // Removing index.html's queue stub rather than replacing it with a real bridge is what makes
    // every call from Kotlin a no-op - FirebaseWebAnalyticsTracker guards on this global existing -
    // and it releases whatever the stub had already buffered.
    delete globalThis.__coupleMomentsAnalytics;
    console.debug("Couple Moments: analytics disabled (no Firebase configuration in this build).");
    """.trimIndent() + "\n"

val generateFirebaseWebInit =
    tasks.register("generateFirebaseWebInit") {
        group = "firebase"
        description = "Generates firebase-init.js from the Firebase Web configuration in the environment."

        val outputDir = layout.buildDirectory.dir("generated/firebase/wasmJsMain/resources")
        val missingKeys = firebaseWebMissingKeys
        val script =
            if (missingKeys.isEmpty()) {
                firebaseInitScript(libs.versions.firebaseJsSdk.get(), firebaseWebConfig)
            } else {
                firebaseDisabledScript(missingKeys)
            }

        // The script text is the task's only real input: change a secret and the file is
        // rewritten; leave it alone and the task is UP-TO-DATE.
        inputs.property("script", script)
        outputs.dir(outputDir)

        doLast {
            if (missingKeys.isNotEmpty()) {
                logger.lifecycle(
                    "webApp: Firebase Web analytics disabled - missing ${missingKeys.joinToString()}. " +
                        "Set the FIREBASE_WEB_* environment variables (see this module's build.gradle.kts).",
                )
            }
            val file = outputDir.get().file("firebase-init.js").asFile
            file.parentFile.mkdirs()
            file.writeText(script)
        }
    }

// The Web (wasmJs) entry point - mirrors androidApp/iosApp's role for Android/iOS: a thin
// platform-specific wrapper around `app`'s shared `App()` composable. The wasmJs target,
// toolchain and ktlint setup all come from the convention plugin above.
kotlin {
    sourceSets {
        wasmJsMain.dependencies {
            implementation(project(":app"))
            // `implementation(project(":app"))` isn't transitive, so app's own Compose deps don't
            // reach this module's compile classpath - ComposeViewport needs its own dependency
            // here regardless.
            implementation(compose.ui)
        }

        // firebase-init.js is generated, never checked in. Registering the task itself (rather
        // than just its output directory) is what makes wasmJsProcessResources depend on it, so
        // the file exists before webpack copies the resources into the distribution.
        wasmJsMain.get().resources.srcDir(generateFirebaseWebInit)
    }
}
